import '../models/place.dart';
import '../models/story.dart';

class MockDataService {
  // 本地图片资源列表 (用于首页精选专题)
  static const List<String> _localImages = [
    'assets/images/nature/a close up of a sand dune with a sky background.jpg',
    'assets/images/nature/a group of antelope standing in the desert.jpg',
    'assets/images/nature/aerial photo of green trees.jpg',
    'assets/images/nature/blue starry night.jpg',
    'assets/images/nature/damiano-baschiera-d4feocYfzAM-unsplash.jpg',
    'assets/images/nature/degleex-ganzorig-wQImoykAwGs-unsplash.jpg',
    'assets/images/nature/florian-schindler-xvldTo5fvrU-unsplash.jpg',
    'assets/images/nature/green Northern Lights at night.jpg',
    'assets/images/nature/jeremy-bishop-EwKXn5CapA4-unsplash.jpg',
    'assets/images/nature/le-mucky-4isDWQY0kHI-unsplash.jpg',
    'assets/images/nature/lin-qiu-yi-wan-IEn7ifEeMKM-unsplash.jpg',
    'assets/images/nature/luobing-42Ah4zCgT-w-unsplash.jpg',
    'assets/images/nature/luobing-gRF1pO679ws-unsplash.jpg',
    'assets/images/nature/riccardo-chiarini-2VDa8bnLM8c-unsplash.jpg',
    'assets/images/nature/simon-fitall-5ditmO9_ae0-unsplash.jpg',
    'assets/images/nature/time lapse photography of body of water.jpg',
    'assets/images/nature/trees surrounded by body water during daytime.jpg',
    'assets/images/nature/wil-stewart-pHANr-CpbYM-unsplash.jpg',
  ];

  // 美食专用本地图片列表
  static const List<String> _foodImages = [
    'assets/images/food/a bowl of food with a garnish on top of it.jpg',
    'assets/images/food/a white plate topped with vegetables and meat.jpg',
    'assets/images/food/cooked food served on black plate.jpg',
    'assets/images/food/dish on white ceramic plate.jpg',
    'assets/images/food/enjoying-a-brunch-together.jpg',
    'assets/images/food/indian-feast-with-butter-chicken-chicken-tandoori-lamb-curry-vegetable-curry-samosas-pakoras.jpg',
    'assets/images/food/person holding black ceramic bowl with vegetable salad.jpg',
    'assets/images/food/Three plates of food on a table.jpg',
  ];

  // 住宿专用本地图片列表
  static const List<String> _stayImages = [
    'assets/images/stay/a bed sitting under a window in a bedroom.jpg',
    'assets/images/stay/A couple of beds sitting in a bedroom next to a window.jpg',
    'assets/images/stay/a woman standing on a bed in a bedroom.jpg',
    'assets/images/stay/a-lodge-sits-elevated-on-a-bank-overlooking-a-muddy-river-the-lodging-features-a-dark-roof.jpg',
    'assets/images/stay/black leather chairs.jpg',
    'assets/images/stay/Cozy bedroom with a large bed and bedside table.jpg',
    'assets/images/stay/People socialize in a cozy, library-like room.jpg',
  ];

  // 根据ID获取本地图片 (用于首页精选专题)
  static String _getLocalImage(String id) {
    final hash = id.hashCode.abs();
    final index = hash % _localImages.length;
    return _localImages[index];
  }

  // 根据ID获取美食图片
  static String _getFoodImage(String id) {
    final hash = id.hashCode.abs();
    final index = hash % _foodImages.length;
    return _foodImages[index];
  }

  // 根据ID获取住宿图片
  static String _getStayImage(String id) {
    final hash = id.hashCode.abs();
    final index = hash % _stayImages.length;
    return _stayImages[index];
  }

  static List<Place> getMockPlaces() {
    return [
      // 美食类别 - 重新设计
      Place(
        id: '7',
        name: '成都火锅',
        category: '美食',
        description: '正宗川味火锅，麻辣鲜香，体验地道成都味道',
        imageUrl: _getFoodImage('place_7'),
        location: '四川·成都',
        rating: 4.8,
        tags: ['火锅', '川菜', '麻辣'],
      ),
      Place(
        id: '8',
        name: '广式茶楼',
        category: '美食',
        description: '传统粤式茶点，一盅两件的悠闲时光',
        imageUrl: _getFoodImage('place_8'),
        location: '广东·广州',
        rating: 4.6,
        tags: ['茶点', '粤菜', '传统'],
      ),

      // 住宿类别 - 重新设计
      Place(
        id: '9',
        name: '丽江古城客栈',
        category: '住宿',
        description: '纳西风情客栈，体验古城慢生活',
        imageUrl: _getStayImage('place_9'),
        location: '云南·丽江',
        rating: 4.5,
        tags: ['古城', '客栈', '纳西文化'],
      ),

      // 打卡类别 - 重新设计
      Place(
        id: '10',
        name: '798艺术区',
        category: '打卡',
        description: '北京文艺地标，当代艺术与工业遗产的碰撞',
        imageUrl:
            'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=600&fit=crop&q=80',
        location: '北京·798',
        rating: 4.4,
        tags: ['艺术', '文创', '拍照'],
      ),
    ];
  }

  static List<Story> getMockStories() {
    return [
      // 自然类故事 - 精选模块显示
      Story(
        id: '1',
        title: '在云南的那些日子',
        author: '旅行者小王',
        imageUrl: _getLocalImage('story_1'),
        category: '自然',
        discoveryCategory: '自然',
        content:
            '云南的天空总是那么蓝，每一天都有新的惊喜。从大理的洱海到丽江的古城，从香格里拉的雪山到西双版纳的热带雨林，云南用它独特的魅力征服了每一个到访的旅人...',
        likes: 234,
        location: '云南',
        tags: ['云南', '自然', '旅行'],
        createdAt: DateTime.now().subtract(Duration(days: 3)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=wang',
      ),
      Story(
        id: '2',
        title: '海岛慢生活指南',
        author: '海风',
        imageUrl: _getLocalImage('story_2'),
        category: '自然',
        discoveryCategory: '自然',
        content:
            '放慢脚步，感受海岛的每一个瞬间。清晨的第一缕阳光洒在海面上，椰林摇曳，海风轻抚。在这里，时间仿佛静止，只有海浪声在诉说着永恒的故事...',
        likes: 312,
        location: '海南',
        tags: ['海岛', '度假', '慢生活'],
        createdAt: DateTime.now().subtract(Duration(days: 5)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=haifeng',
      ),
      Story(
        id: '3',
        title: '古镇的慢时光',
        author: '阿木',
        imageUrl: _getLocalImage('story_3'),
        category: '文化',
        discoveryCategory: '文化',
        content: '走在青石板路上，时间仿佛静止了。古镇的每一块砖瓦都诉说着历史的故事，小桥流水，白墙黛瓦，这里是江南水乡最美的诗篇...',
        likes: 267,
        location: '江南',
        tags: ['古镇', '文化', '慢生活'],
        createdAt: DateTime.now().subtract(Duration(days: 7)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=amu',
      ),
      Story(
        id: '4',
        title: '西藏朝圣之路',
        author: '行者无疆',
        imageUrl: _getLocalImage('story_4'),
        category: '文化',
        discoveryCategory: '文化',
        content: '踏上西藏朝圣之路，感受雪域高原的神圣与纯净。布达拉宫的金顶在阳光下闪闪发光，转经筒的声音在风中回响...',
        likes: 456,
        location: '西藏',
        tags: ['朝圣', '文化', '雪域'],
        createdAt: DateTime.now().subtract(Duration(days: 2)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=xizang',
      ),
      Story(
        id: '5',
        title: '新疆天山雪莲',
        author: '雪山行者',
        imageUrl: _getLocalImage('story_5'),
        category: '自然',
        discoveryCategory: '自然',
        content: '在天山深处寻找雪莲花，体验新疆壮美的自然风光。雪峰连绵，草原辽阔，这里是大自然最纯净的馈赠...',
        likes: 389,
        location: '新疆',
        tags: ['天山', '雪莲', '自然'],
        createdAt: DateTime.now().subtract(Duration(days: 4)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=tianshan',
      ),
      Story(
        id: '6',
        title: '海南椰风海韵',
        author: '椰林漫步',
        imageUrl: _getLocalImage('story_6'),
        category: '自然',
        discoveryCategory: '自然',
        content: '海南的椰风海韵让人沉醉，碧海蓝天，椰影摇曳。在这个热带天堂里，时间仿佛变得缓慢而美好...',
        likes: 523,
        location: '海南',
        tags: ['海滩', '椰林', '热带'],
        createdAt: DateTime.now().subtract(Duration(days: 6)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=hainan',
      ),
      Story(
        id: '7',
        title: '张家界的奇峰异石',
        author: '登山客',
        imageUrl: _getLocalImage('story_7'),
        category: '户外',
        discoveryCategory: '户外',
        content: '天门山的玻璃栈道，挑战你的勇气。站在悬崖边，脚下是万丈深渊，眼前是壮美的山川，这是勇敢者的游戏...',
        likes: 523,
        location: '湖南',
        tags: ['张家界', '登山', '户外'],
        createdAt: DateTime.now().subtract(Duration(days: 8)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=dengshan',
      ),
      Story(
        id: '8',
        title: '苏州园林雅韵',
        author: '园林爱好者',
        imageUrl: _getLocalImage('story_8'),
        category: '文化',
        discoveryCategory: '文化',
        content: '苏州园林是中国古典园林的典范，一步一景，移步换景。在这里感受古人的智慧与审美...',
        likes: 412,
        location: '江苏',
        tags: ['园林', '古典', '文化'],
        createdAt: DateTime.now().subtract(Duration(days: 1)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=suzhou',
      ),
      Story(
        id: '9',
        title: '内蒙古草原风情',
        author: '草原牧歌',
        imageUrl: _getLocalImage('story_9'),
        category: '自然',
        discoveryCategory: '自然',
        content: '策马奔腾在辽阔的草原上，感受蒙古族的豪迈与热情。蓝天白云下，牛羊成群，这就是草原的魅力...',
        likes: 567,
        location: '内蒙古',
        tags: ['草原', '蒙古族', '骑马'],
        createdAt: DateTime.now().subtract(Duration(days: 9)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=caoyuan',
      ),
      Story(
        id: '10',
        title: '厦门鼓浪屿文艺之旅',
        author: '文艺青年',
        imageUrl: _getLocalImage('story_10'),
        category: '文化',
        discoveryCategory: '文化',
        content: '鼓浪屿的每一条小巷都充满文艺气息，钢琴博物馆、各式咖啡店，这里是文艺青年的天堂...',
        likes: 634,
        location: '福建',
        tags: ['鼓浪屿', '文艺', '咖啡'],
        createdAt: DateTime.now().subtract(Duration(days: 10)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=gulangyu',
      ),

      // 美食类故事 - 归类为娱乐
      Story(
        id: '11',
        title: '夜市美食探险',
        author: '吃货小李',
        imageUrl: _getLocalImage('story_11'),
        category: '美食',
        discoveryCategory: '娱乐',
        content: '夜幕降临，夜市的烟火气最动人。从臭豆腐到珍珠奶茶，从牛肉面到小笼包，每一样美食都承载着当地的文化和记忆...',
        likes: 198,
        location: '台湾',
        tags: ['夜市', '美食', '小吃'],
        createdAt: DateTime.now().subtract(Duration(days: 11)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=xiaoli',
      ),
      Story(
        id: '12',
        title: '重庆火锅江湖',
        author: '火锅达人',
        imageUrl: _getFoodImage('story_12'),
        category: '美食',
        discoveryCategory: '娱乐',
        content: '重庆火锅的麻辣鲜香，是山城人民的灵魂美食。红油翻滚，香气四溢，一口下去就是满满的幸福感...',
        likes: 789,
        location: '重庆',
        tags: ['火锅', '麻辣', '山城'],
        createdAt: DateTime.now().subtract(Duration(days: 12)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=chongqing',
      ),
      Story(
        id: '13',
        title: '兰州拉面传奇',
        author: '面食专家',
        imageUrl: _getFoodImage('story_13'),
        category: '美食',
        discoveryCategory: '娱乐',
        content: '一碗正宗的兰州拉面，清汤、白萝卜、红辣椒、绿香菜、黄面条，五色搭配，这就是西北的味道...',
        likes: 456,
        location: '甘肃',
        tags: ['拉面', '西北', '传统'],
        createdAt: DateTime.now().subtract(Duration(days: 13)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=lanzhou',
      ),
      Story(
        id: '14',
        title: '上海小笼包',
        author: '沪上美食家',
        imageUrl: _getFoodImage('story_14'),
        category: '美食',
        discoveryCategory: '娱乐',
        content: '上海小笼包皮薄馅大，汤汁鲜美。轻咬一口，鲜美的汤汁在口中爆开，这就是海派美食的精髓...',
        likes: 623,
        location: '上海',
        tags: ['小笼包', '海派', '精致'],
        createdAt: DateTime.now().subtract(Duration(days: 14)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=shanghai',
      ),
      Story(
        id: '15',
        title: '北京烤鸭文化',
        author: '京城老饕',
        imageUrl: _getFoodImage('story_15'),
        category: '美食',
        discoveryCategory: '娱乐',
        content: '北京烤鸭是京城的招牌美食，皮脆肉嫩，配上甜面酱和黄瓜丝，卷在薄饼里，满口留香...',
        likes: 567,
        location: '北京',
        tags: ['烤鸭', '京菜', '传统'],
        createdAt: DateTime.now().subtract(Duration(days: 15)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=beijing',
      ),

      // 住宿类故事 - 归类为户外
      Story(
        id: '16',
        title: '雪山下的温泉',
        author: '温泉爱好者',
        imageUrl: _getStayImage('story_16'),
        category: '住宿',
        discoveryCategory: '户外',
        content: '在雪山脚下泡温泉，是冬日最大的享受。热气腾腾的温泉水，远山如黛，这是大自然给予的最好礼物...',
        likes: 356,
        location: '日本',
        tags: ['温泉', '雪山', '度假'],
        createdAt: DateTime.now().subtract(Duration(days: 16)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=wenquan',
      ),
      Story(
        id: '17',
        title: '森林里的民宿',
        author: '森林系',
        imageUrl: _getStayImage('story_17'),
        category: '住宿',
        discoveryCategory: '户外',
        content: '被绿色包围的小木屋，是逃离城市的最佳选择。清晨被鸟鸣声唤醒，推开窗就是满眼的绿意...',
        likes: 289,
        location: '云南',
        tags: ['民宿', '森林', '木屋'],
        createdAt: DateTime.now().subtract(Duration(days: 17)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=senlin',
      ),
      Story(
        id: '18',
        title: '海边的度假酒店',
        author: '度假达人',
        imageUrl: _getStayImage('story_18'),
        category: '住宿',
        discoveryCategory: '户外',
        content: '推开窗就是大海，这才是度假的正确打开方式。海风轻抚，椰影摇曳，在这里忘记所有的烦恼...',
        likes: 567,
        location: '海南',
        tags: ['酒店', '海边', '度假'],
        createdAt: DateTime.now().subtract(Duration(days: 18)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=dujia',
      ),
      Story(
        id: '19',
        title: '古城里的客栈',
        author: '客栈老板',
        imageUrl: _getStayImage('story_19'),
        category: '住宿',
        discoveryCategory: '文化',
        content: '在丽江古城，找一家安静的客栈发呆。四合院里的天井，木质的楼梯，还有那份难得的宁静...',
        likes: 423,
        location: '云南',
        tags: ['客栈', '古城', '丽江'],
        createdAt: DateTime.now().subtract(Duration(days: 19)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=kezhan',
      ),
      Story(
        id: '20',
        title: '山顶的星空帐篷',
        author: '露营专家',
        imageUrl: _getStayImage('story_20'),
        category: '住宿',
        discoveryCategory: '户外',
        content: '躺在帐篷里看星空，浪漫又刺激。远离城市的光污染，在这里你能看到最纯净的星空...',
        likes: 689,
        location: '新疆',
        tags: ['帐篷', '星空', '露营'],
        createdAt: DateTime.now().subtract(Duration(days: 20)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=luying',
      ),

      // 打卡类故事 - 归类为娱乐
      Story(
        id: '21',
        title: '寻找城市里的小确幸',
        author: '城市漫游者',
        imageUrl: _getLocalImage('story_21'),
        category: '打卡',
        discoveryCategory: '娱乐',
        content: '在繁忙的都市中，总有一些角落让人心动。可能是街角的咖啡店，可能是公园里的一棵树，小确幸就在身边...',
        likes: 189,
        location: '上海',
        tags: ['城市', '小确幸', '发现'],
        createdAt: DateTime.now().subtract(Duration(days: 21)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=chengshi',
      ),
      Story(
        id: '22',
        title: '山间的秘密花园',
        author: '花花',
        imageUrl: _getLocalImage('story_22'),
        category: '打卡',
        discoveryCategory: '娱乐',
        content: '藏在山里的花海，美得让人窒息。春天的时候，整个山谷都被花朵覆盖，像是童话里的秘密花园...',
        likes: 421,
        location: '云南',
        tags: ['花海', '秘密', '山间'],
        createdAt: DateTime.now().subtract(Duration(days: 22)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=huahua',
      ),
      Story(
        id: '23',
        title: '沙漠星空露营',
        author: '星空追梦人',
        imageUrl: _getLocalImage('story_23'),
        category: '打卡',
        discoveryCategory: '娱乐',
        content: '在沙漠中仰望星空，感受宇宙的浩瀚。没有城市的喧嚣，只有无垠的星空和内心的宁静...',
        likes: 445,
        location: '内蒙古',
        tags: ['沙漠', '星空', '露营'],
        createdAt: DateTime.now().subtract(Duration(days: 23)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=xingkong',
      ),
      Story(
        id: '24',
        title: '网红书店打卡',
        author: '书虫小姐',
        imageUrl: _getLocalImage('story_24'),
        category: '打卡',
        discoveryCategory: '文化',
        content: '这家书店不仅有书，还有诗和远方。精心设计的空间，温暖的灯光，让人忍不住想要停留...',
        likes: 567,
        location: '北京',
        tags: ['书店', '网红', '文艺'],
        createdAt: DateTime.now().subtract(Duration(days: 24)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=shuchong',
      ),
      Story(
        id: '25',
        title: '艺术馆的光影世界',
        author: '艺术青年',
        imageUrl: _getLocalImage('story_25'),
        category: '打卡',
        discoveryCategory: '文化',
        content: '在艺术馆里，每一束光都是一幅画。现代艺术与传统文化的碰撞，创造出无限的可能性...',
        likes: 489,
        location: '上海',
        tags: ['艺术馆', '光影', '艺术'],
        createdAt: DateTime.now().subtract(Duration(days: 25)),
        avatarUrl: 'https://api.dicebear.com/7.x/avataaars/png?seed=yishu',
      ),
      // 补充美食类帖子
      Story(
        id: '26',
        title: '广州早茶文化体验',
        author: '茶点师傅',
        imageUrl: _getFoodImage('story_26'),
        category: '美食',
        discoveryCategory: '娱乐',
        content: '一盅两件，叹早茶。虾饺、烧卖、肠粉、凤爪，每一样都是广州人的心头好。在茶楼里，品的不只是茶点，更是一种生活态度...',
        likes: 567,
        location: '广州',
        tags: ['早茶', '粤菜', '茶点'],
        createdAt: DateTime.now().subtract(Duration(days: 26)),
        avatarUrl:
            'https://api.dicebear.com/7.x/avataaars/png?seed=chadianshifu',
      ),
      Story(
        id: '27',
        title: '西安美食探店记',
        author: '陕西老乡',
        imageUrl: _getFoodImage('story_27'),
        category: '美食',
        discoveryCategory: '娱乐',
        content: '肉夹馍、凉皮、羊肉泡馍，西安的美食让人流连忘返。走在回民街，空气中弥漫着各种香味，这就是古都的味道...',
        likes: 623,
        location: '西安',
        tags: ['肉夹馍', '陕西美食', '回民街'],
        createdAt: DateTime.now().subtract(Duration(days: 27)),
        avatarUrl:
            'https://api.dicebear.com/7.x/avataaars/png?seed=shanxilaoxiang',
      ),
      // 补充住宿类帖子
      Story(
        id: '28',
        title: '草原蒙古包住宿体验',
        author: '草原牧民',
        imageUrl: _getStayImage('story_28'),
        category: '住宿',
        discoveryCategory: '户外',
        content: '住在蒙古包里，感受草原的辽阔。夜晚围着篝火唱歌跳舞，白天骑马驰骋在草原上，这是最原始的快乐...',
        likes: 534,
        location: '内蒙古',
        tags: ['蒙古包', '草原', '篝火'],
        createdAt: DateTime.now().subtract(Duration(days: 28)),
        avatarUrl:
            'https://api.dicebear.com/7.x/avataaars/png?seed=caoyuanmumin',
      ),
      // 补充打卡类帖子
      Story(
        id: '29',
        title: '网红咖啡店打卡',
        author: '咖啡爱好者',
        imageUrl: _getLocalImage('story_29'),
        category: '打卡',
        discoveryCategory: '娱乐',
        content: '这家咖啡店的装修太有格调了！复古的家具，温暖的灯光，还有那杯拉花精致的拿铁，每一处都是拍照的好地方...',
        likes: 712,
        location: '成都',
        tags: ['咖啡', '网红店', '拍照'],
        createdAt: DateTime.now().subtract(Duration(days: 29)),
        avatarUrl:
            'https://api.dicebear.com/7.x/avataaars/png?seed=kafeiaihaozhe',
      ),
    ];
  }

  static List<String> getAIQuestions() {
    return [
      '推荐一些适合周末的旅行目的地',
      '帮我规划一次3天2夜的短途旅行',
      '有什么好吃的当地特色美食推荐？',
      '最近有什么有趣的户外活动吗？',
    ];
  }
}
