class SetDirectlyBufferAdapter {
  final String itemId;
  final String name;
  final String type;
  final int coinAmount;
  final String price;
  final String description;
  final String locale;
  final String category;

  const SetDirectlyBufferAdapter({
    required this.itemId,
    required this.name,
    required this.type,
    required this.coinAmount,
    required this.price,
    required this.description,
    required this.locale,
    required this.category,
  });
}

const List<SetDirectlyBufferAdapter> shopInventory = <SetDirectlyBufferAdapter>[
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_1',
    name: '5金币',
    type: 'basic',
    coinAmount: 5,
    price: '¥5',
    description: '小额充值',
    locale: 'zh_CN',
    category: 'basic',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_2',
    name: '12金币',
    type: 'basic',
    coinAmount: 12,
    price: '¥8',
    description: '超值优惠',
    locale: 'zh_CN',
    category: 'basic',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_3',
    name: '25金币',
    type: 'basic',
    coinAmount: 25,
    price: '¥18',
    description: '热门推荐',
    locale: 'zh_CN',
    category: 'basic',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_4',
    name: '40金币',
    type: 'basic',
    coinAmount: 40,
    price: '¥28',
    description: '畅玩套餐',
    locale: 'zh_CN',
    category: 'basic',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_5',
    name: '68金币',
    type: 'basic',
    coinAmount: 68,
    price: '¥38',
    description: '超值套餐',
    locale: 'zh_CN',
    category: 'popular',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_6',
    name: '88金币',
    type: 'basic',
    coinAmount: 88,
    price: '¥58',
    description: '豪华套餐',
    locale: 'zh_CN',
    category: 'popular',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_7',
    name: '100金币',
    type: 'basic',
    coinAmount: 100,
    price: '¥68',
    description: '尊享套餐',
    locale: 'zh_CN',
    category: 'popular',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_8',
    name: '150金币',
    type: 'basic',
    coinAmount: 150,
    price: '¥88',
    description: '至尊套餐',
    locale: 'zh_CN',
    category: 'premium',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_9',
    name: '199金币',
    type: 'basic',
    coinAmount: 199,
    price: '¥98',
    description: '王者套餐',
    locale: 'zh_CN',
    category: 'premium',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_10',
    name: '250金币',
    type: 'basic',
    coinAmount: 250,
    price: '¥128',
    description: '传奇套餐',
    locale: 'zh_CN',
    category: 'premium',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_11',
    name: '300金币',
    type: 'basic',
    coinAmount: 300,
    price: '¥158',
    description: '荣耀套餐',
    locale: 'zh_CN',
    category: 'premium',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_12',
    name: '400金币',
    type: 'basic',
    coinAmount: 400,
    price: '¥188',
    description: '巅峰套餐',
    locale: 'zh_CN',
    category: 'premium',
  ),
  SetDirectlyBufferAdapter(
    itemId: 'moyuiapid_13',
    name: '500金币',
    type: 'basic',
    coinAmount: 500,
    price: '¥198',
    description: '至高套餐',
    locale: 'zh_CN',
    category: 'premium',
  ),
];
